import { FaPhoneAlt } from "react-icons/fa"
export const brand = "kolayplan"

export const kolayplan = {
    title: "kolayplan nedir?",
    subtitle: "bir diyetisyenin ihtiyacı olan her şey!",
    description: [
        "kolayplan sana ve danışanlarına özel olarak hazırlanan bir yazılımdır. kısaca kullanırken kimse bizim ismimizi görmez :) bu proje tamamen seninle alakalı.",
        "danışanlarını  tek bir platform üzerinde yönetebilir ve artık whatsapptan tek tek danışanlarından bilgi alıp klasörlerin içinde vakit kaybetmekten kurtulabilirsin.",
        "sana hem kurumsal bir görünüm kazandırıyoruz.",
        "sana ve danışanlarına vakit kazandırıyoruz.",
    ],
    button: {name: "İLETİŞİM", icon: FaPhoneAlt, link:"/iletisim"}
}

export const confidentiallyAgreement = `Gizlilik ve KVKK Politikası
kolayplan Aydınlatma Metni
KOLAYPLAN.NET GİZLİLİK ve KİŞİSEL VERİLERİN KORUNMASI POLİTİKASI

Gizlilik ve Kişisel Verilerin Korunması Politikasının Amacı
Bu Gizlilik ve Kişisel Verilerin Korunması Politikası kolayplan ünvan işlettiği kolayplan.net adresli internet hizmetinin ne gibi kişisel veriler topladığını, bu bilgilerin nasıl kullanıldığını, gerekmesi halinde kolayplan'ın bu bilgileri kimlerle paylaşabileceğini, kolayplan’ın topladığı/işlediği/sakladığı kişisel verilerinize ilişkin haklarınızın ne olduğunu, bu hakları nasıl kullanabileceğinizi ve elektronik ticari iletiler konusundaki tercihlerinizi nasıl değiştirebileceğinizi açıklamaktadır.

Kişisel verilerin işlenmesine ilişkin hukuki dayanak
kolayplan’ın sunduğu internet hizmeti olan kolayplan.net, 5651 Sayılı İnternet Ortamında Yapılan Yayınların Düzenlenmesi ve Bu Yayınlar Yoluyla İşlenen Suçlarla Mücadele Edilmesi Hakkında Kanun ve ilgili ikincil mevzuat, 6563 Sayılı Elektronik Ticaretin Düzenlenmesi Hakkında Kanun ve ilgili ikincil mevzuat, 5237 Sayılı Türk Ceza Kanunu ve 6698 Sayılı Kişisel Verilerin Korunması Kanunu ve benzeri kanun ve yönetmeliklerden kaynaklanan yükümlülüklerini yerine getirebilmek için kişisel verilerinizi (ad, soyad, doğum tarihi, cep telefonu numarası, e-posta, cinsiyet, adres ve kişiyi doğrudan veya dolaylı olarak tanımlamaya yönelik bazı kişisel bilgileri) toplamaktadır. 

Bu veriler açık rızanıza istinaden, burada belirtilen amaçlar dışında kullanılmamak kaydı ile her türlü tedbir alınarak toplanacak, işlenecek ve saklanacaktır.

İşlenen kişisel verilerinizin neler olduğunu, yurt içi veya yurt dışında kişisel verilerin aktarıldığı üçüncü kişileri öğrenmek, verilerinizi değiştirmek, güncellemek ve/veya silmek kolayplan.net web sitesi, mobil uygulaması ve mobil sitesi içindeki “Bilgilerim” bölümünden hesabınıza erişebilir veya iletisim@kolayplan.net e-posta adresi üzerinden bizimle irtibata geçebilirsiniz. 6698 Sayılı Kişisel Verilerin Korunması Kanunu madde 11 uyarınca sahip olduğunuz diğer haklar saklıdır.
6563 Sayılı Elektronik Ticaretin Düzenlenmesi Hakkında Kanun uyarınca; onayın geri alındığına ilişkin kayıtlar bu tarihten itibaren 1 yıl; ticari elektronik iletinin içeriği ve gönderiye ilişkin diğer her türlü kayıt ise gerektiğinde ilgili bakanlığa sunulmak üzere 3 yıl saklanacaktır. Süre geçtikten sonra kişisel verileriniz şirketimiz tarafından üzerine silinir, yok edilir veya anonim hale getirilir.

Çerez (Cookie) Kullanımı
kolayplan.net yasal yükümlülüğü çerçevesinde, işbu Gizlilik ve Kişisel Verilerin Korunması Politikası ile belirlenen amaçlar dışında kullanılmamak şartı ile gezinme bilgilerinizi toplayacak, işleyecek, üçüncü kişilerle paylaşacak ve güvenli olarak saklayacaktır. Gezinme bilgilerinizi toplama amacıyla kullandığımız çerezler (cookie) hakkında bilgi, kolayplan.net web ve mobil sitesine ilk girişinizde veya mobil uygulamasını telefonunuza veya tabletinize yüklediğinizde “açılır pencere (pop-up ekran)” ile verilecektir.

Çerezler, kolayplan.net'i ziyaret ettiğinizde veya mobil uygulamayı cep telefonunuza yüklediğinizde veya mobil sitesi’nden bağlandığınızda, internet tarayıcınız tarafından yüklenen ve bilgisayarınız, cep telefonunuz veya tabletinizde saklanan küçük bilgi parçacıklarını içeren metin dosyalarıdır.

kolayplan.net, size özel tanıtım yapmak, promosyonlar ve pazarlama teklifleri sunmak, web sitesinin veya mobil uygulamanın içeriğini size göre iyileştirmek ve/veya tercihlerinizi belirlemek amacıyla; site üzerinde gezinme bilgilerinizi ve/veya site üzerindeki üyelik kullanım geçmişinizi izlemektedir. kolayplan.net farklı yöntemlerle veya farklı zamanlarda site üzerinde toplanan bilgileri eşleştirebilir ve bu bilgileri üçüncü taraflar gibi başka kaynaklardan alınan bilgilerle birlikte kullanabilir. Söz konusu eşleştirme ve kullanma yalnızca işbu Gizlilik ve Kişisel Verilerin Korunması Politikası ile belirlenen amaçlar ve kapsam dahilinde kalacaktır.

Çerez Çeşitleri
kolayplan.net web sitesinde, mobil uygulamasında ve mobil sitesinde oturum çerezleri ve kalıcı çerezler kullanmaktadır. Oturum kimliği çerezi, tarayıcınızı kapattığınızda sona erer. Kalıcı çerez ise sabit diskinizde uzun bir süre kalır. İnternet tarayıcınızın "yardım" dosyasında verilen talimatları izleyerek veya “www.allaboutcookies.org” veya “www.youronlinechoices.eu” adresini ziyaret ederek kalıcı çerezleri kaldırabilir ve hem oturum çerezlerini hem de kalıcı çerezleri reddedebilirsiniz. Kalıcı çerezleri veya oturum çerezlerini reddederseniz, web sitesini, mobil uygulamayı ve mobil sitesini kullanmaya devam edebilirsiniz, fakat web sitesinin, mobil uygulamanın ve mobil sitesinin tüm işlevlerine erişemeyebilirsiniz veya erişiminiz sınırlı olabilir. Mobil uygulamada söz konusu durum değişkenlik gösterebilmektedir.
kolayplan.net çerezleri yaptığınız tercihleri hatırlamak ve web sitesi/mobil uygulama/mobil sitesi kullanımınızı kişiselleştirmek için kullanır (örneğin parolanızı kaydeden ve oturumunuzun sürekli açık kalmasını sağlayan, daha sonraki ziyaretlerinizde sizi tanıyan çerezler). kolayplan.net çerezleri ayrıca kolayplan.net’e nereden bağlandığınız, hangi içeriği görüntülediğiniz ve ziyaretinizin süresi gibi kolayplan.net'i nasıl kullandığınızı takip etmemizi sağlar. Buna ek olarak, ilgi alanlarınıza ve size daha uygun içerik ve kampanyalar sunmak için hedeflenmiş reklam/tanıtım amacıyla kullanır. kolayplan.net çerezler yoluyla elde edilen bilgileri kullanıcılardan toplanan kişisel verilerle eşleştirir.

kolayplan.net üçüncü taraf çerezlerini reklam ve yeniden hedefleme için nasıl kullanmaktadır?
kolayplan.net çerezleri ayrıca; arama motorlarını, kolayplan.net'i ve kolayplan.net’in reklam verdiği web sitelerini ziyaret ettiğinizde ilginizi çekebileceğini düşündüğü reklamları size sunabilmek için kullanabilir. Bu reklamları sunarken, kolayplan.net’in sizi tanıyabilmesi amacıyla tarayıcınıza benzersiz bir üçüncü taraf çerezi yerleştirilebilir. kolayplan.net’in web sitesi/mobil uygulaması/mobil sitesi ayrıca; Google, Inc. ("Google") tarafından sağlanan bir web analizi hizmeti olan Google Analytics kullanmaktadır. Google Analytics, çerezleri ziyaretçilerin web sitesini/mobil uygulamayı/mobi sitesini nasıl kullandıklarını analiz etmek amacıyla kullanır. Bu web sitesini/mobil uygulamayı/mobil sitesini kullanımınızla ilgili bilgiler (IP adresiniz dahil) Google'a aktarılarak Google tarafından ABD'deki sunucularda saklanmaktadır. Google bu bilgileri web sitesini/mobil uygulamayı/mobil sitesini kullanımınızı değerlendirmek, kolayplan.net web sitesi/mobil uygulama/mobil site faaliyetini derlemek ve web sitesi/mobil uygulama/mobil sitesifaaliyeti ve internet kullanımıyla ilgili başka hizmetler sağlamak amacıyla kullanacaktır. Fakat IP adresinizi Google tarafından depolanan diğer verilerle eşleştirmeyecektir. Google Analytics kullanımı hakkında daha fazla bilgi için (reddetme seçenekleri dahil), şu adresi ziyaret edebilirsiniz:http://www.google.com/intl/tr/policies/privacy/#infocollect
Bunun yanı sıra sizler için ilginizi çekebilecek reklamları size sunabilmek amacıyla, Facebook ile de özel hedef kitle oluşturmak amacıyla, işbu Gizlilik/Kişisel Verilerin Korunması Politikası ve İletişim İzni’ni kabul etmekle, kolayplan.net ile paylaşmış olduğunuz kişisel verilerinizden e-posta adresiniz Facebook ile paylaşılmaktadır. e-Posta adresinizi Facebook'a yüklemeden ve iletmeden önce, hash yöntemiyle Facebook tarafından yerel olarak sistemimizde şifrelenir. Facebook ile paylaşılan Hash Yöntemiyle Şifrelenen e-posta adresiniz, yalnızca eşleştirme işlemi için kullanılacaktır. Üçüncü taraflarla veya diğer reklam verenlerle paylaşılmaz ve eşleştirme işlemi tamamlandıktan sonra mümkün olan en kısa sürede Facebook sistemlerinden silinirler. Facebook, (a) kişisel veriniz Facebook sistemlerinde bulunduğu sürece verilerin güvenliğini ve bütünlüğünü korumak ve (b) Facebook sistemlerinde bulunan kişisel verinize yanlışlıkla veya yetkisiz olarak erişilmesine ve verinizin yanlışlıkla veya yetkisiz olarak kullanılmasına, değiştirilmesine veya ifşa edilmesine karşı korumak için geliştirilen teknik ve fiziksel güvenlik önlemlerini de içerecek şekilde, özel hedef kitlenizi ("özel hedef kitleniz") oluşturan Hash Yöntemiyle Şifrelenen Verilerin ve Facebook Kullanıcı Kimliği koleksiyonunun gizliliğini ve güvenliğini sağlayacaktır. Ayrıca, izniniz olmadan veya yasalar gerektirmediği sürece, Facebook üçüncü taraflara veya diğer reklam verenlere özel hedef kitleniz için erişim veya bilgi vermez, özel hedef kitle bilgilerinizi kullanıcılarımız hakkındaki bilgilere eklemez veya ilgi alanına dayalı profiller oluşturmaz ya da özel hedef kitlenizi size hizmet sunmanın haricinde kullanmaz. Facebook özel hedef kitleler koşulları için https://www.facebook.com/ads/manage/customaudiences/tos.php?_=_ adresini, Facebook Gizlilik İlkeleri için https://www.facebook.com/privacy/explanation adresini ziyaret edebilirsiniz.

Resmi Makamlarla Kişisel Veri Paylaşımı
kolayplan.net ziyaretinize veya üyeliğe ilişkin kişisel verilerinizi ve gezinme bilgileriniz gibi trafik bilgilerinizi; güvenliğiniz ve kolayplan'ın yasalar karşısındaki yükümlülüğünü ifa etmesi amacıyla yasal olarak bu bilgileri talep etmeye yetkili olan kamu kurum ve kuruluşları ile paylaşabilecektir.

Kişisel Verilerin Korunmasına İlişkin Önlemler
kolayplan kişisel verilere yetkisiz erişimi engellemek için gerekli tüm önlemleri almaktadır.
kolayplan kişisel verilerinizi gizli tutacağını taahhüt eder. Yine de alınan önlemlere rağmen kolayplan.net'e yapılabilecek saldırılar nedeniyle verilerin üçüncü kişilerin eline geçmesi durumunda, kolayplan bu durumu derhal sizlere ve Kişisel Verileri Koruma Kurulu’na bildirir ve gerekli önlemleri alır.

kolayplan işbu Gizlilik ve Kişisel Verilerin Korunması Politikası'nda değişiklik yapabilir. İşbu Gizlilik ve Kişisel Verilerin Korunması Politikası'ndaki değişikliklerden haberdar olmanız için kolayplan.net üyelerine gerekli bilgilendirme yapılacaktır. Kullanıcılar, Üyelik/Kişisel bilgilerini ve iletişim tercihlerini her zaman sisteme giriş yaparak güncelleyebilirler. Bu konudaki taleplerinizi iletisim@kolayplan.net e-posta adresine e-posta göndererek iletebilirsiniz. 

Uygulanacak Hukuk, Yetkili Mahkeme ve İcra Daireleri
İşbu Gizlilik/Kişisel Verilerin Korunması Politikası ve İletişim İzni, Türkiye Cumhuriyeti kanunlarına tabidir. Gizlilik/Kişisel Verilerin Korunması Politikası ve İletişim İzni’nin uygulanmasından doğabilecek her türlü uyuşmazlığın çözümünde İstanbul Merkez Mahkeme ve İcra Daireleri yetkilidir.

İletişim İzni
İşbu Gizlilik/Kişisel Verilerin Korunması Politikası ve İletişim İzni’ni kabul etmekle, bizimle paylaşılmasına rıza göstermiş olduğunuz kişisel verilerinizin, tarafınıza çeşitli avantajların sağlanıp sunulabilmesi ve size özel tanıtım, promosyon, reklam, satış, pazarlama, anket ve benzer amaçlı her türlü elektronik iletişimin telefon, kısa mesaj (SMS), e-posta ve benzeri yollarla yapılması ve diğer iletişim mesajlarının gönderilmesi amacıyla; toplanmasına, saklanmasına, işlenmesine, kullanılmasına ve kolayplan'ın sözleşme ilişkisi içerisinde olduğu üçüncü kişilere aktarımına izin vermiş bulunmaktasınız.
`

export const lightningText = `Aydınlatma Metni
Kişisel Verilerin İşlenmesine Yönelik Aydınlatma Metni (“Aydınlatma Metni”) ile kolayplan ünvan.  (“kolayplan”) olarak, 6698 sayılı Kişisel Verilerin Korunması Kanunu (“KVKK”) uyarınca, Veri Sorumlusu sıfatıyla, sizi KVKK kapsamındaki aydınlatma yükümlülüğümüz çerçevesinde, aşağıda tanımlanan Kişisel Verilerinizin toplanma yöntemleri ve hukuki sebepleri, Kişisel Verilerinizi koruma yöntemlerimiz ve politikamız, işlenen Kişisel Veri örnekleri, veri sorumlusunun kimliği, Kişisel Verilerin işlenme amaçları, Kişisel Verilerinizin üçüncü kişilere ve/veya yurtdışına aktarımı ve KVKK kapsamında size tanınan haklara ilişkin olarak bilgilendirmek istiyoruz.
KVKK Kapsamında kişisel veri kimliği belirli veya belirlenebilir gerçek kişiye ilişkin her türlü bilgiyi (“Kişisel Veri”) ve bunun bir özel türü olan Özel Nitelikli Kişisel Veri ise, ırk, etnik köken, siyasi düşünce, felsefi inanç, din, mezhep veya diğer inançlar, kılık ve kıyafet, dernek, vakıf ya da sendika üyeliği, sağlık, cinsel hayat, ceza mahkûmiyeti ve güvenlik tedbirleriyle ilgili verileri ile biyometrik ve genetik verileri (“Özel Nitelikli Kişisel Veri”) ifade eder. Bu kapsamda Kişisel Veri tanımı Özel Nitelikli Kişisel Verilerinizi de kapsamaktadır.
1.	Kişisel Verilerinizi Toplanma Yöntemimiz ve Hukuki Sebepler
kolayplan, yürütmüş olduğu tüm Kişisel Veri işleme faaliyetlerinde KVKK başta olmak üzere ilgili mevzuatta aranan tüm yükümlüklere uygun olarak hareket etmekte ve Kişisel Verilerinizin güvenli bir şekilde barındırılması ve Kişisel Verilerinizin hukuka aykırı biçimde kullanılmasının önlenmesi için gerekli güvenlik tedbirlerini almaktadır.
KVKK gereğince, aşağıda sayılanlar ve bunlara ileride eklenebilecek sair kanallar vasıtasıyla Kişisel Verilerinizi otomatik yahut otomatik olmayan yollarla, sözlü, yazılı veya elektronik şekilde aşağıdaki yöntemlerle toplamakta ve KVKK Madde 5.1, Madde 5.2, Madde 6.2 ve Madde 6.3 kapsamında işlemekteyiz:
•	https://kolayplan.net adresli internet sitemiz ve ileride kurulabilecek sair internet sitelerimiz veya yazılımın çalıştığı web sitesi (“İnternet Sitesi”) üzerinden aşağıdaki sayfalar başta olmak ancak bunlarla sınırlı olmaksızın otomatik veya otomatik olmayan yollarla elektronik olarak,
•	İnternet Sitesi’nde yer alan Kullanım Şartnamesi’nin onaylanması ile gerçekleştirilen kayıtlar,
•	İnternet Sitesinde cihazlarınızla iletişim sağlayan çerezler (“Çerez”) kanalıyla otomatik veya otomatik olmayan yollarla elektronik olarak (çerezlerle ekseriyetle anonim veri toplanmaktadır),
•	Çeşitli sosyal medya kanalları üzerinde kolayplan adına işletilen hesaplar (“Sosyal Medya”) kanalıyla otomatik veya otomatik olmayan yollarla elektronik olarak,
•	E-posta adreslerimiz (“E-posta”) üzerinden yürütülen yazışmalar, kolayplan’a sair amaçlarla gönderilen kısa mesajlar (“SMS”) veya multi medya mesajları (“MMS”) dahil sair iletişim yöntemleri ile her türlü iletişim araçları (“İletişim Araçları”) kanalıyla otomatik veya otomatik olmayan yollarla yazılı, sözlü veya elektronik olarak,
•	kolayplan’a ait veya kolayplan bünyesinde olmayıp üçüncü kişiler tarafından kurulan veya faaliyette bulunan tüm hizmet satış ve pazarlama ağı (“Satış Ağı”) kanalıyla, satış, pazarlama ve satış sonrası hizmetler kapsamında otomatik veya otomatik olmayan yollarla sözlü, yazılı veya elektronik olarak,
•	kolayplan tarafından veya kolayplan bünyesinde olmayıp üçüncü kişiler tarafından kurulan veya faaliyette bulunan tüm sair hizmet satışı sonrası hizmetler ağımız (“SSH”) kanalıyla otomatik veya otomatik olmayan yollarla sözlü, yazılı veya elektronik olarak,
•	Çağrı merkezlerimiz (“Çağrı Merkezi”) kanalıyla otomatik veya otomatik olmayan yollarla sözlü veya elektronik olarak,
•	kolayplan’ın hizmet verdiği yahut hizmet aldığı grup şirketleri, iş ortakları, üretici firmalar veya hizmet/ürün tedarik ettiği firmalar gibi üçüncü kişiler kanalıyla otomatik veya otomatik olmayan yollarla sözlü veya elektronik olarak.
•	Tarafınızca internet siteniz, sosyal medya yahut sair Kişisel Verilerinizi alenileştirdiğiniz kanallar üzerinden otomatik veya otomatik olmayan yollarla sözlü veya elektronik olarak.
2.	Hangi Kişisel Verilerinizi İşlemekteyiz
•	Bize Sağladığınız Kişisel Veriler: Yukarıda belirtilen kanallar üzerinden herhangi bir şekilde tarafımızla paylaştığınız her türlü Kişisel Veriyi işbu Aydınlatma Metni içerisinde yer alan esaslar ve amaçlar dahilinde işlemekteyiz. Bu kapsamda, internet sitemiz ve yazılımınıza ait internet siteniz üzerinden üyelik kaydı yahut hizmet satın alırken akdedilen profesyonel sözleşmeler ve mesafeli satış sözleşmeleri kapsamında paylaştığınız ad-soyad, doğum tarihi, diploma, öğrenim durumu, T.C. Kimlik numarası, telefon numarası, e-mail adresi, adres gibi Kişisel Verileriniz, Özel Nitelikli Kişisel Verileri de barındırabilecek Kişisel Verileriniz, Çağrı Merkezimiz ile gerçekleştirdiğiniz görüşmeler kapsamında paylaştığınız Kişisel Verileriniz, tarafımıza İletişim Araçları vasıtası ile ilettiğiniz Kişisel Verileriniz yahut bir hizmetin ifası için paylaştığınız Kişisel Verileriniz, bir yarışmaya veya ankete katıldığınızda sağladığınız Kişisel Verileriniz örnek olarak gösterilebilir.
•	Otomatik Yollarla Toplanan Kişisel Veriler Dahil Sair Bilgiler: Otomatik arama makineleri, görüntü ve ses kaydı cihazları veya Çerezler vasıtasıyla otomatik şekilde toplanan Kişisel Verinizi işbu Aydınlatma Metni içerisinde yer alan esaslar ve amaçlar dahilinde işlemekteyiz. Çerezler vasıtası ile toplanan veriler siz üye olmadığınız müddetçe anonim şekilde toplanmaktadır ve Kişisel Veri mahiyetinde değildir. Bu kapsamda bilgisayarınızı internete bağlamak için kullanılan Internet protokolü (IP) adresi; internet tarayıcısı eklenti türleri ve sürümleri, e-postalara ilişkin alındı ve okundu teyitleri; oturum açma; e-posta adresi; şifre; internet tarayıcısı türü ve sürümü gibi bilgisayar ve bağlantı bilgileri; saat ayarı; işletim sistemi ve platformu; satın alma geçmişi, konum, İnternet Sitelerimiz üzerinden girdiğiniz URL’ler, çerez numarası; görüntülediğiniz veya aradığınız ürünler ve müşteri hizmetleri numaramızı aramak için kullanılan her türlü telefon numarası ve güvenlik yahut hizmet kalitesini artırmak amacı ile alınan ses ve görüntü kayıtları gibi bilgiler ve Kişisel Veriler örnek gösterilebilir. Ayrıca Flash çerezleri ve internet tarayıcısı kanallarıyla sahteciliği önleme ve tanı amaçlı olarak cihazınızı tanımamıza yardımcı olacak Kişisel Veri niteliğinde olmayan teknik bilgileri de işleyebilmekteyiz.
•	Diğer Kaynaklardan Alınan Kişisel Veriler de Dahil Sair Bilgiler: Sizin hakkınızda diğer kaynaklardan da bilgi alabilir ve işbu Aydınlatma Metni içerisinde yer alan esaslar ve amaçlar dahilinde Kişisel Veri işleyebiliriz. Bu kapsamda, internet sitenizde yahut sair kanalda alenileştirdiğiniz mesleki bilgileriniz ve iletişim bilgileriniz, sosyal medya araçları üzerinden İnternet Siteleri’ne yapılan üyelik kayıtlarında sizin ilgili sosyal medya araçlarına daha önce vermiş olduğunuz izninize dayalı olarak tarafımızla paylaşılan Kişisel Verileriniz, iş ortaklarımız, bize Kişisel Verileriniz aktarılması kapsamında ilgili veri sorumlularına vermiş olduğunuz izne dayalı olarak topladığımız güncellenmiş adres bilgileri; hesap bilgileri, satın alma, sayfa görüntüleme bilgileri; aranan terim ve arama sonuçları gibi bilgiler, ödenmiş listelemeler (Sponsorlu Bağlantılar gibi) dahil olmak üzere arama sonuçları ve bağlantıları ve sahteciliğini önlemeye ve tespit etmeye yardımcı olmak ve bazı müşterilere ödeme kolaylığı sağlamak toplanan hesap numarası ve sair ödeme aracı bilgileri örnek olarak gösterilebilir.
3.	Veri Sorumlusunun Kimliği
Yukarıda anılan kanallar vasıtasıyla paylaştığınız Kişisel Verileriniz bakımından Veri Sorumlusu, kolayplan ünvan.
4.	Kişisel Verilerinizin İşlenme Amaçları
İşbu Aydınlatma Metni’nde anılan kanallardan, anılan yöntemlerle toplanan Kişisel Verileriniz aşağıdaki amaçlar dahilinde kolayplan tarafından işlenmektedir:
•	KVKK Madde 5.2 ve Madde 6.3 kapsamında;
•	Kanuni yükümlülüklerimizi (vergi mevzuatı, tüketicilerin korunmasına yönelik mevzuat, iş sağlığı ve güvenliği mevzuatı, borçlar kanunu, ticaret kanunu ve sair mevzuat, telekomünikasyon mevzuatı, bankacılık mevzuatı gibi) yerine getirmek amacıyla: e-fatura, e-arşiv kapsamında yahut tüketici mevzuatının gerekli kıldığı durumlarda verilerinizin işlenmesi ve ilgili düzenleme kapsamında atfedilebilecek her türlü sair işlemeler örnek verilebilir.
•	Fiili imkânsızlık nedeniyle rızanızı açıklayamayacak durumda olmanız halinde veya rızanıza hukuki geçerlilik tanınmayan sizin yahut bir başkasının hayat veya beden bütünlüğünün korunması için zorunlu olan amaçlarla: satış temsilcimizin yanında meydana gelen meydana bir sağlık sorunu sonucunda acil bir müdahale gerekmesi halinde Kişisel Verilerinizin bilinciniz yerinde olmaksızın işlenmesi ve ilgili düzenleme kapsamında atfedilebilecek her türlü sair işlemeler örnek verilebilir.
•	Bir sözleşmenin kurulması veya ifası amacıyla: tarafımızca katılımcılarımıza Katılım Şartnamesi kapsamında taahhüt edilen tüm hizmetler dahil olmak üzere İnternet Siteleri ve Çağrı Merkezi aracılığıyla kolayplan tarafından sunulmakta olan tüm hizmetlerin tarafınıza sağlanması, bu kapsamda gerekli durumlarda iletişime geçilmesi, üyelik etkinleştirme kapsamında üyelik ve müşteri desteği sağlanması, bu kapsamda gerekli durumlarda iletişime geçilmesi gibi yükümlülüklerimizin ifası kapsamında ve ilgili düzenleme kapsamında atfedilebilecek her türlü sair işlemeler örnek verilebilir.
•	Hukuki yükümlülüklerimizi yerine getirmek amacıyla: İnternet Siteleri, İletişim Araçları yahut Çağrı Merkezi üzerinden kolayplan hizmetlerine ilişkin sizden gelecek soru, şikayet ve bildirimlerin cevaplanması ve çözüme kavuşturulması kapsamında işlemeler ve ilgili düzenleme kapsamında atfedilebilecek her türlü sair işlemeler örnek verilebilir.
•	Bir hakkın tesisi, kullanılması veya korunması amacıyla: satış ve satış sonrası hizmetler kapsamında kayıtların delil olarak tutulması kapsamında yapılan işlemeler ve ilgili düzenleme kapsamında atfedilebilecek her türlü sair işlemeler örnek verilebilir.
•	Temel hak ve özgürlüklerinize zarar vermeksizin, meşru menfaatlerimizi korumak amacıyla: ses kaydı alınan Çağrı Merkezi tarafından hizmetin kalitesinin ölçülmesi, bu kapsamda ilettiğiniz taleplerinizin değerlendirilmesi ve çözüme kavuşturulması gibi işlemeler ve ilgili düzenleme kapsamında atfedilebilecek her türlü sair işlemeler örnek verilebilir.
Ayrıca alenileştirdiğiniz Kişisel Verileriniz de açık rızanız olmaksızın yukarıda belirtilen sair amaçlarla işlenebilmektedir. Sosyal Medya kanalları, internet siteniz ve sair mecralarda alenileştirmiş olduğunuz Kişisel Verileriniz tarafımızca işlenmesi ve ilgili düzenleme kapsamında atfedilebilecek her türlü sair işlemeler bu duruma örnek gösterilebilir.
•	Yukarıdaki kanallardan, yine yukarıda ifade edilen yöntemlerle toplanan Kişisel Verileriniz KVKK Madde 5.1 ve Madde 6.2 kapsamında açık rızanızın alınması şartı ile aşağıdaki amaçlarla da işlenebilir:
•	İnternet Sitesi’nde yer alan sayfalar üzerinden Yorum Bölümleri aracılığıyla ilgili alanlarda anonim olmaksızın paylaşmış olduğunuz kişisel sağlık verileriniz ve cinsel hayat verileriniz gibi Özel Nitelikli Kişisel Verilerinizin sunulan hizmetlerin şeffaflığının sağlanması, İnternet sitelerimizin faailiyetlerinin yerine getirilmesi amacıyla işlenmesi.
•	İnternet reklamcılığı, targeting, re-targeting (=hedefleme ve yeniden hedefleme), çapraz satış, kampanya, fırsat ve ürün/hizmet reklamları gibi size özel ürün ve hizmetlere yönelik fırsatların sunulması amacıyla işlenmesi,
•	İnternet Siteleri’ini ziyaretiniz esnasında kişiye özel içerik sağlanması amacıyla işlenmesi,
•	satış, tele-satış ve pazarlama faaliyetleri için yapılacak başta sizlere özel reklam, kampanya, avantajlar ve diğer faydaların sunulması ve sair pazarlama ve CRM (Müşteri İlişkileri Yönetimi) çalışmalarının yürütülmesi amacıyla işlenmesi,
•	yeni ürün ve hizmet modellerinin oluşturulması amacıyla işlenmesi,
•	elektronik ticari iletilerin (kampanya, newsletter, müşteri memnuniyet anketleri, ürün ve hizmet reklamları gibi) gönderimi amacıyla işlenmesi,
•	hediye ve promosyon ve sair dergi/süreli yayın gönderimi amacıyla işlenmesi,,
•	kurumsal iletişim ve bu kapsamda sair etkinlik ve davetlerin düzenlenmesi ve bunlar hakkında bilgilendirme yapılması amacıyla işlenmesi,
•	Ayrıca Özel Nitelikli Kişisel Verilerinizin de açık rızanızın varlığı halinde KVKK Madde 5.2’de belirlenen amaçlarla ve burada (i)’den (viii)’e kadar belirlenen amaçlarla işlenmesi.
5.	Kişisel Verilerinizin İşlenme Süresi
İşbu Aydınlatma Metni’nde anılan kanallar vasıtasıyla kolayplan ile paylaşmış olduğunuz Kişisel Veriler, KVKK başta olmak üzere Kişisel Verilerin korunmasına ilişkin mevzuata ve diğer mevzuatta zorunlu kılınan sürelere uygun şekilde her halükârda yukarıdaki meşru amaçlar ortadan kalkmadığı müddetçe işlenecektir.
6.	Kişisel Verilerinizin Üçüncü Kişilere ve/veya Yurtdışına Aktarılması
kolayplan, işbu Aydınlatma Metni’nde anılan kanallardan, anılan yöntemlerle toplanan Kişisel Verilerinizi, KVKK ve sair mevzuat kapsamında ve işbu Aydınlatma Metni’nde anılan amaçlar dahilinde üçüncü kişilere veya yurtdışına aktarabilir. Kişisel verileriniz:
•	Yukarıda KVKK Madde 5.2 ve Madde 6.3 kapsamında belirlenen amaçların varlığı halinde, yurtiçinde ve başta AB ülkeleri, Amerika, İngiltere, OECD ülkeleri, Hindistan, Çin ve Rusya olmak üzere yurtdışında bulunan depolama, arşivleme, bilişim teknolojileri desteği (sunucu, hosting, program, bulut bilişim), güvenlik, çağrı merkezi gibi alanlarda destek aldığımız üçüncü kişilerle, işbirliği yapılan ve/veya hizmet alınan Grup Şirketleri, iş ortakları, tedarikçi firmalar, bankalar, finans kuruluşları, hukuk, vergi vb. benzeri alanlarda destek alınan danışmanlık firmaları ve belirlenen amaçlarla aktarımın gerekli olduğu diğer ilişkili taraflar ile yetkili kurum ve kuruluşlara aktarılabilmektedir;
•	Yukarıda KVKK Madde 5.1 ve Madde 6.3 kapsamında yurtiçinde ve başta AB ülkeleri, Amerika, İngiltere, OECD ülkeleri, Hindistan, Çin ve Rusya olmak üzere yurtdışında bulunan belirlenen amaçlar bakımından açık rızanızın alınması şartı ile, pazarlama şirketleri, Grup Şirketleri, pazarlama desteği veren üçüncü kişi hizmet firmalarına (e-posta gönderimi, kampanya oluşturulması amacı ile reklam firmaları, CRM desteği veren firmalara açık rızanıza istinaden aktarılabilmektedir.
Ayrıca açık rızanıza istinaden kolayplan’ın bir kısmının veya varlıklarının (marka, alan adı ve sair ticari işletme unsurları dahil ancak bunlarla sınırlı olmaksızın) satılması durumunda Kişisel Verileriniz devralan gerçek ya da tüzel kişilere, bunların paydaşları, iş ortakları, aracıları, danışmanları da dahil olmak üzere yurtiçi ve yurtdışındaki üçüncü kişilere devrin gerektirdiği ölçüde aktarılabilir, işlem sürecinde bu üçüncü kişiler tarafından gerekli değerlendirmenin yapılması ile sınırlı ölçüde işlenebilir ve devir halinde devralan taraf varlıklarla birlikte bu varlıklara bağlı değerler olan Kişisel Verilerinizi kendisi veri sorumlusu olacak şekilde işlemeye devam edebilir.
7.	Kişisel Verilerinize Erişim ve KVKK Kapsamında Haklarınız
KVKK madde 11 uyarınca kolayplan’a başvurarak;
•	Kişisel Verilerinizin işlenip işlenmediğini öğrenme,
•	Kişisel Verileriniz işlenmişse buna ilişkin bilgi talep etme,
•	Kişisel Verilerinizin işlenme amacını ve bunların amacına uygun kullanılıp kullanılmadığını öğrenme,
•	Yurt içinde veya yurt dışında Kişisel Verilerinizin aktarıldığı üçüncü kişileri bilme,
•	Kişisel Verilerinizin eksik veya yanlış işlenmiş olması hâlinde bunların düzeltilmesini isteme,
•	Amaç, süre ve meşruiyet prensipleri dâhilinde değerlendirilmek üzere Kişisel Verilerinizin işlenmesini gerektiren sebeplerin ortadan kalkması halinde silinmesini veya yok edilmesini isteme,
•	Kişisel Verilerinizin düzeltilmesi, silinmesi ya da yok edilmesi halinde bu işlemlerin Kişisel Verilerin aktarıldığı üçüncü kişilere bildirilmesini isteme,
•	İşlenen Kişisel Verilerinizin münhasıran otomatik sistemler vasıtasıyla analiz edilmesi durumunda aleyhinize bir sonucun ortaya çıkması halinde bu sonuca itiraz etme,
•	Kişisel Verilerinizin kanuna aykırı olarak işlenmesi ve bu sebeple zarara uğramanız hâlinde zararın giderilmesini talep etme,
haklarına sahipsiniz.
Bu kapsamda, yukarıdaki haklarınıza ilişkin talebinizi Kişisel Verileri Koruma Kurumu tarafından belirlenen şartları taşıyacak şekilde oluşturarak aşağıda verilen ve zaman zaman değişebilecek olan e-posta adresimize bize daha önce bildirdiğiniz ve sistemimizde kayıtlı olan e-posta adresinizden göndereceğiniz e-posta ile (lütfen sistemimizde kayıtlı e-posta adresinizi kontrol ediniz) veya güvenli elektronik imzalı veya mobil imzalı olarak kep adresimize yahut yine aşağıda yer alan ve zaman zaman değişebilecek olan posta adresimize ıslak imzalı bir dilekçe ile elden ya da noter aracılığıyla teslim edebilir ve ileride bunlara eklenebilecek Kişisel Verileri Koruma Kurumu tarafından belirlenen diğer yöntemlerle gönderebilirsiniz. Lütfen güncel başvuru yöntemlerini başvuru öncesinde mevzuattan teyit ediniz. kolayplan, talebin niteliğine göre talebi en kısa sürede ve en geç 30 (otuz) gün içinde ücretsiz olarak sonuçlandıracaktır. Taleplerin kolayplan tarafından sonuçlandırılmasına ilişkin ayrıca bir maliyet doğması hâlinde Kişisel Verileri Koruma Kurulunca belirlenen tarifedeki ücretler kolayplan tarafından talep edilebilir.
Posta adresi             	:
E-posta adresi         	    : 
Kep adresi   	        	: 
`

export const sellingAgreement = `Mesafeli Satış Sözleşmesi
6502 Sayılı Tüketicinin Korunması Hakkında Kanun Gereğince Bilgilendirme Formu
Sağlayıcının isim ve unvanı, açık adresi, telefon ve diğer iletişim bilgileri :

Unvan : kolayplan
Adres :
Telefon : 
E¬mail : 

MADDE 1 - Giriş
İşbu Sözleşme’de kolayplan tarafından kolayplan.net web sitesi (“Web Sitesi”) kanalıyla Hizmet Alıcılar’a sunulan hizmetlerin Hizmet Alıcılar tarafından Web Sitesi kanalıyla sipariş edilmesi ve bunların satışına ilişkin hüküm ve şartlar belirlenmektedir.
Hizmet Sağlayıcı ve Hizmet Alıcı bundan böyle tek başına “Taraf” ve birlikte “Taraflar” olarak anılacaktır.
“1 Aylık Paket” adı altında verilen kolayplan yazılımının içeriği aşağıdaki gibidir: 
1.	
2.	
3.	
“6 Aylık Paket” adı altında, “1 Aylık Paket”’ tekilere ek olarak verilen yazılımın içeriği aşağıdaki gibidir:
1.	
2.	
3.	
“12 Aylık Paket” adı altında, “6 Aylık Paket”’tekilere ek olarak verilen yazılımın içeriği aşağıdaki gibidir:
1.	
2.	
3.	
 
MADDE 2 - Tanımlar
 
Bu Sözleşme’de aşağıda belirtilen terimler kullanılmaktadır:
1.	Hizmet Sağlayıcı – Adres - Ünvan ifade eder.. 
2.	Hizmet Alıcı – Hizmet Sağlayıcı’nın paket hizmetlerini kullanan ve işbu Sözleşme’deki şartlar çerçevesinde bu hizmetleri sipariş edecek olan, söz konusu hizmetlerin verilmesi için imzalanacak sözleşmenin tarafı olan ve işbu Sözleşme’ye uymakla yükümlü olan her türlü gerçek kişi, işletme veya tüzel kişiyi ifade eder. 
3.	kolayplan (“Yazılım” veya “Sistem”) - www.kolayplan.net web sitesi üzerinden satışı yapılır ve, işletmelere özel olarak kurulan web sitesi üzerinden randevu, danışan ve finansal verilerini yönetmesi maksadıyla sunulan işletme yönetim uygulamasını ifade eder.
4.	Danışan - Hizmet Alıcı’nın kolayplan yazılımı aracılığıyla hizmet verdiği kişilerdir.
5.	Hizmet/Hizmetler – Her türlü yasal hakları Hizmet Sağlayıcı’ya ait olan ve Kullanıcı’ya kolayplan.net adresi üzerinden sunulan yönetim yazılımıdır.
6.	Paket/Paketler – Hizmet Alıcı'nın somut ihtiyaçları dikkate alınarak öngörülen ve işbu Sözleşme’de belirtilen ödeme koşullarının gerçekleşmesini müteakip belirli bir süre için Hizmet Alıcı’nın Profil’inin kullanımına sunulan ek fonksiyonlar grubunu ifade eder. İşbu fonksiyonlar grubuna 1 Aylık Paket / 6 Aylık Paket ve 12 Aylık Paket adı verilir. 
7.	Ödeme Dönemi – Hizmet Alıcı’nın kendisine sağlanan hizmetler için ödeme yaptığı dönemi ifade eder. Ödeme Dönemi Hizmet Sağlayıcı tarafından belirlenecektir. 
8.	Sözleşme – Taraflar arasında Sipariş verme yoluyla işbu Sözleşme’de belirtilen şartlar dahilinde Paket hizmeti sağlanması için imzalanan sözleşmeyi ifade eder.
9.	SMS Modülü - Hizmet Alıcı tarafından kolayplan aracılığıyla SMS başlığı belirlenerek, metni hizmet alıcı tarafından belirlenmiş ve yasal yükümlülüğü tamamen Hizmet Alıcıya ait olan, gönderim altyapısı ve faturalandırılması EVYAPAN BİLGİ TEKNOLOJİLERİ TİC. LTD. ŞTİ. tarafından sağlanan sms gönderim sistemidir.
 
MADDE 3 - Sözleşmeleri İmzalama ve Sonlandırma Prosedürü
 
1.	Taraflar arasında Sözleşme akdedilmeden önce Hizmet Alıcı işbu Sözleşme’ye göre bir Sipariş verip aşağıdaki yollardan biriyle Hizmet Sağlayıcı’ya imzalı siparişi iletir ve Hizmet Sağlayıcı da teslim aldığını teyit eder.
Siparişin iletilme şekilleri;
1.	imzalı Sipariş’in Hizmet Sağlayıcı tarafından belirtilen Hizmet Alıcı e-mail adresine gönderilmesi
2.	imzalı Sipariş’in Hizmet Sağlayıcı’nın ticari temsilcisine doğrudan gönderilmesi veya elden teslim edilmesi veya
3.	imzalı Sipariş’in kolayplan.net üzeriden Hizmet Alıcı tarafından dijital ortamda, kayıt işlemi sırasında veya sonrasında “Sözleşme’yi okudum, kabul ediyorum” maddesini işaretlemek suretiyle, işlemi gerçekleştirdiği IP adresi Hizmet Sağlayıcı tarafından kayıt altına alınarak  kabul edilmesi
2.	Paketler’in güncel fiyatları kolayplan.net adresindeki fiyat listesinden temin edilebilir. Hizmet Sağlayıcı fiyat listesini herhangi bir zamanda tek taraflı olarak değiştirme hakkını saklı tutar. Fiyat listesindeki değişiklikler Hizmet Alıcı için güncel Sözleşme’nin uzatılmasıyla geçerli olacaktır. 
3.	Sözleşme’nin geçerlilik süresi 12 aydır. Sözleşme’nin geçerlilik süresinin sona ermesi üzerine, Taraflar’dan biri Sözleşme’yi uzatmak istemediğini diğer Taraf’a bildirmediği sürece Sözleşme, aksi Taraflarca veya bu Sözleşme kapsamında belirlenmediği sürece, aynı koşullarla ve fesih bildirimi yapılana kadar bir aylık sürelerle yenilenir. Bildirim en geç Sözleşme’nin bitimine 1 ay kala yapılmalıdır. 
4.	Sipariş’in alınmasından sonra Hizmet Sağlayıcı, Sipariş’i yerine getirmek için gerekli teknik ve insan kaynaklarını kullanarak hizmetleri vermeye başlar. Hizmet Sağlayıcı tarafından hizmetlerin devreye alınması, Hizmet Alıcı’nın Sipariş’inin kabul edildiği anlamına gelir.
5.	Hizmet Alıcı her zaman için Sözleşme’yi Hizmet Sağlayıcı’ya bildirim yaparak tek taraflı feshetme hakkına sahiptir. Sözleşme, Hizmet Sağlayıcı’nın fesih bildirimini aldığı ilgili hizmet ayının sonunda sonlanacaktır. 
6.	Hizmet Alıcı’nın Sözleşme’de öngörülen yükümlülüklerini yerine getirmemesi durumunda Hizmet Sağlayıcı mahkemeye başvurmaya ve ihbar süresinin uygulanmasına gerek olmaksızın Sözleşmeyi derhal tek taraflı olarak ve tazminatsız sonlandırma hakkına sahip olacaktır. Böyle bir durumda Hizmet Sağlayıcı Hizmet Alıcı’dan Madde 9’da tanımlanan cezai tazminat ile ilgili hükümler uygulanacaktır. 
7.	İşbu Sözleşme kapsamında belirtilen bildirimlerin alındığı tarih bildirimin Hizmet Sağlayıcı’nın veya Hizmet Alıcının aşağıda belirtilen adreslerinde teslim alındığı tarih olarak kabul edilecektir. Bildirimlerin yazılı olması gerekir, aksi halde bildirimler geçersiz sayılacaktır. Bir belgenin Hizmet Alıcı tarafından Siparişte belirtilen adreste ve Hizmet Sağlayıcı tarafından ise Sözleşme’de belirtilen adreste teslim alınması durumunda Taraflar söz konusu belgenin yazılı olarak gönderildiğini kabul edecektir. Şu kadar ki TTK 18/3 hükümleri saklıdır. Adres değişikliklerinin diğer Taraf’a 10 gün içerisinde bildirilmemesi durumunda bu madde kapsamında belirtilen adreslere yapılan tebligatlar usulüne uygun olarak yapılmış sayılacaktır. 
8.	Hizmet Alıcı Sipariş’te belirtilen Paket hizmetinin ilgili olduğu Hizmet Alıcı web sitesinde yer alan bilgi ve materyallerin doğruluğunu ve bu bilgilerin hiçbir yasa hükmünü ve/veya üçüncü şahısların haklarını ihlal etmediğini beyan ve taahhüt eder. İşbu beyan ve taahhüte aykırı bir durumun ortaya çıkması halinde 3. kişilerden gelecekler dahil her türlü talepten bizzat Hizmet Alıcı sorumlu olup Hizmet Sağlayıcı’nın rücu hakkı saklıdır.
9.	Hizmet Alıcı, kolayplan yazılımını kullanmak veya fonksiyonları üzerindeki blokajı kaldırmak için gerekli materyalleri zamanında temin edecektir. Hizmet Alıcı’nın yukarıda belirtilen materyali Sipariş’in imza tarihinden itibaren 7 iş günü içerisinde temin etmemesi Hizmet Sağlayıcı tarafından hizmetlerin verilmesini durdurmayacaktır. Profil Sipariş geçildiğinde alınan bilgilere veya materyallere dayanarak yayınlanacaktır.Hizmet Alıcı hizmetin bu durumda usulüne uygun olarak verildiğini kabul edeceğini ve bu konuda Hizmet Sağlayıcı’ya herhangi bir talepte bulunma hakkına sahip olmayacağını kabul eder.
10.	Hizmet Alıcı birden fazla Profil için “Başlangıç Paket”, “Standart Paket”, “Full Paket” ve “Kurumsal Paket” satın aldığı takdirde, Paket hizmetinin verilmeye başlama zamanı satın alınan Profiller’den biri için bu hizmetlerin verilmeye başlandığı tarih olarak kabul edilecektir.
11.	Taraflar, Hizmet Sağlayıcı’nın hizmet sunumunu gerçekleştireceği Web Sitesi’nin (alan adı da dahil) tasarımını, arayüzlerini, panellerini, görsellerini ve fonksiyonlarını Hizmet Sağlayıcı’nın değiştirebileceği konusunda mutabıktırlar. Taraflar, Web Sitesi’ndeki tasarım ve görsellerin tüm fikri mülkiyet haklarına Hizmet Sağlayıcı’nın sahip olacağı konusunda mutabıktırlar. Hizmet Alıcı’ya ilişkin sunulan bilgilerin Hizmet Sağlayıcı veya bağlı kişi veya şirketleri (ana ortakları veya hakim ortakları) tarafından arşiv, yedekleme, bilgi saklama ve istatistiki sebeplerle işlenebileceğini ve bunların iş geliştirme amacıyla Hizmet Sağlayıcı veya bağlı kişi veya şirketleri (ana ortakları veya hakim ortakları) tarafından iş ortakları ve üçüncü kişiler ile paylaşabileceğini Hizmet Alıcı kabul eder. Taraflar Hizmet Sağlayıcı’nın, hizmet sunumunu gerçekleştireceği Web Sitesi’nde yer alan mecralara Hizmet Sağlayıcı’nın faaliyetleri ile ilgili ve mevzuata uygun tanıtım, reklamlar alabileceği ve verebileceği, blog kanalları açabileceği, forumlara erişim sağlayabileceği konusunda mutabıktırlar. 
12.	Hizmet, yazılım sistemi ve “1 Aylık Paket”, “6 Aylık Paket”, “12 Aylık Paket” veya ile ilgili fonksiyonlara ilişkin telif hakları da dahil her türlü fikri mülkiyet hakları Hizmet Sağlayıcı’ya aittir.
13.	Hizmet Sağlayıcı tarafından yapılan tüm işlere ilişkin telif hakları ile fikri mülkiyet hakları ile korunan diğer işlerin ve materyallerin bağımsız parçaları olan unsurlara ilişkin telif hakları oluşturuldukları tarihten itibaren Hizmet Sağlayıcıya aittir.
14.	Hizmet Alıcı hizmetlerde sergilenen grafik tasarımlarla ve Hizmetlerle ilgili herhangi bir hak sahibi olmayacaktır.
15.	Hizmet Alıcı girişimsel faaliyetlerin yürütülmesiyle ilgili Hizmetleri kullandığını teyid eder. Tüketicinin korunmasına ilişkin mevzuat uygulanmaz.
 
MADDE 4 - Ödeme Şartları 
 
1.	Paket hizmetler için Hizmet Alıcı tarafından ödenecek bedel her bir Sipariş’te belirtilecektir.
2.	İşbu hizmetlerin temini için ilk fatura Hizmet Alıcı’nın hizmetleri almaya başladığı tarihten itibaren düzenlenecek olup, müteakip faturalar da İlk Fatura Tarihi’ni takip eden 1 er ay aralıklarla düzenlenecektir. Hizmet Alıcı düzenlenen her bir fatura bedelini fatura düzenlenmesini takip eden 14 gün içerisinde ödemekle yükümlü olacaktır. Hizmet aktivasyonu, ilk faturanın ödenmesine müteakiben yapılacaktır.
3.	Hizmet Alıcı’nın Hizmet Sağlayıcı tarafından lisanslı ödeme aracı kuruluşları veya mukim bankaların altyapısını kullanarak oluşturulan online ödeme sistemi ve/veya mail order yoluyla sağladığı kredi kartı bilgileri ile işbu Sözleşme kapsamında Hizmet’in yürürlükte olduğu süre boyunca ya da Sözleşme’nin ilgili hükümleri gereği Sözleşme’nin sona ermesi akabinde düzenleyeceği her bir faturanın tahsilatı otomatik olarak gerçekleştirilecektir. Sözleşme’nin iptali ile birlikte Hizmet Alıcı’nın tahakkuk etmiş başka bir borcu kalmaması halinde otomatik tahsilat sistemi başka bir bildirime gerek kalmaksızın kendiliğinden iptal edilir. Hizmet Alıcı’nın hesabından mükerrer veya sehven bir tahsilat işleminin gerçekleştirilmesi halinde, Hizmet Sağlayıcı’nın Vergi Usul Kanunu uyarınca tutmakla mükellef olduğu hesap kayıtlarının incelenmesine müteakip sehven tahsil edilen bu bedel Hizmet Alıcı’ya iade edilir.
4.	Hizmet Sağlayıcı, Hizmet Alıcı’ya kendi takdirinde olmak üzere indirim sağlayabilir (bu indirimin tutarı ve şartları Paket hizmetlerine ilişkin faturada veya başka bir belgede belirtilir). İndirimin temini ve tutarı Hizmet Sağlayıcı tarafından önerilen ek fonksiyonlara bağlıdır. Özellikle bu indirim Profesyonel’in Hizmet Sağlayıcı’nın kendi web sitesinde (varsa) önerdiği ek fonksiyonları kurmasıyla bağlantılı olabilir. Şüpheye mahal vermemek adına belirtilmelidir ki Hizmet Sağlayıcı tarafından yapılan indirim bunun devamlılık arz edeceği anlamına gelmez. Hizmet Sağlayıcı kendi takdirine bağlı olmak üzere daha önce uyguladığı indirimi her zaman sonlandırma hakkına sahiptir. Böyle bir durumda Hizmet Alıcı’nın hiçbir talep hakkı bulunmamaktadır.
5.	Hizmet Sağlayıcı’nın faturalarında belirtilen Paket hizmetlerinin fiyatı, sağlanan indirimler hariç, herhangi bir stopaj veya kesinti yapılmadan KDV dahil bedel üzerinden tam olarak ödenmelidir. 
6.	Hizmetler için belirtilen ödemenin vadesinde gerçekleştirilmemesi halinde Madde § 9 dördüncü bentte tanımlanan cezai tazminata ilişkin hükümler aynen uygulanır. Hizmet Sağlayıcı’nın cezai tazminatı aşan zararlarını talep etme hakkı saklıdır.
7.	SMS Modülü gönderim hizmeti için kullanılacak SMS paketleri Hizmet Alıcının ilgili SMS paketinin ilgili tarihteki ücretini ödemesinin ardından hesabına yüklenir.
 
MADDE 5 - Verilen Hizmetlerin Türü ve Kapsamı
 
1.	Paket hizmeti, Sipariş’te gösterilen Hizmet Alıcı’ların özel web sitelerine yüklenir.
2.	Web Siteleri’nde Paket hizmetinin aktif hale getirilmesi gereken Hizmet Alıcı’lar Web Sitesi’ne kaydedilmeli ve ayrıca bu kişiler Hizmet Sağlayıcı tarafından belirtilen şartlar doğrultusunda yetki almalıdır.
 
MADDE 6 - Paket Hizmetlerinin Verildiği Şartlar
 
Hizmet Sağlayıcı Paket hizmetlerini Hizmet Alıcı’ya Sipariş’te ve bu Sözleşme’de belirtilen kapsamda ve şartlarda temin edecektir.
1.	Hizmet Sağlayıcı:
1.	Sözleşme’nin geçerlilik süresi içerisinde Hizmet Alıcı tarafından gösterilen Web Siiteleri’nin hizmetlerini aktive edecek ve tutacaktır; 
2.	Hizmet Alıcı’ nın Web Siteleri’ndeki verilerin düzeltimine ilişkin paneli aktive edecektir;
3.	“1 Aylık Paket”, “6 Aylık Paket”, “12 Aylık Paket” aktif duruma getirildiği Web Sitesi’nin taslağının hazırlanmasında, paketin aktivasyon tarihini izleyen 21 gün içinde yardım sağlayacaktır.
2.	Hizmet Alıcı:
1.	Ödemelerini zamanında yapacak;
2.	Web Siteleri’nde tam ve doğru bilgiler tutacak;
3.	Web Siteleri’n’de tuttuğu Kullanıcı kişisel verileri için Kullanıcılardan gerekli izinleri alacak, gerekli izinleri almadan kayıt ettiği kişisel verilerden kaynaklı Hizmet Sağlayıcı’ya gelebilecek her türlü yasal ve cezai yaptırımdan tamamen ve yalnızca Hizmet Alıcı olarak kendisinin sorumlu olduğunu kabul etmiş sayılacak;
4.	Hizmetlerin doğru verilmesi ve özellikle Web Siteleri’nde Hizmet Sağlayıcı tarafından gösterilen şekilde tamamlanması için Hizmet Sağlayıcı ile yakından işbirliği yapacaktır.
5.	SMS Modülü hizmeti kapsamında gönderim yapacağı SMS lerin yasal olarak belirtilen şartları sağladığına emin olacak ve yasal yükümlülüğün kendinde olacağını kabul edecektir.
1.	Taraflardan her biri diğer Taraf hakkında bu Sözleşme’nin ifası dolayısıyla öğrendiği, üçüncü kişilerce yasal yollarla zaten bilinenler dışındaki tüm bilgileri sır olarak kabul etmeyi ve bu bilgileri diğer Taraf’ın yazılı izni olmadan üçüncü kişi ya da kuruluşlara vermemeyi, açıklamamayı, kamuya duyurmamayı ya da bu şekilde sonuçlanacak davranışlardan kaçınmayı taahhüt ederler. Taraflar’ın bu Sözleşme’nin ifası dolayısıyla birbirleri ve Sözleşme konusu hakkında öğrendikleri ve üçüncü kişilerce yasal yollarla zaten bilinenler dışındaki her türlü bilgi bu madde kapsamındadır. Gizliliğin ihlali halinde Taraflar diğer Taraf’ın her türlü zarar ve ziyanını tazmin etmeyi peşinen kabul ve taahhüt eder. İşbu Sözleşme’nin herhangi bir nedenle sona ermesi hali bu maddede yer alan yükümlülüklerin sona ermesine sebep olmaz.
2.	Bu Sözleşme’den kaynaklanan bilgilerin gerek Hizmet Alıcı ve gerekse 3. kişiler tarafından kullanılması veya açıklanması ve Sözleşme’nin ifası ile ilgili olmayan amaçlar için alınması durumunda Hizmet Alıcı her türlü zarar ve talepten bizzat sorumludur.
3.	Hizmet Alıcı, Hizmet Sağlayıcı’nın IT sistemini bu Sözleşme kapsamı dışında kullanamaz. Bu kapsamda 3. kişilerden gelebilecek her türlü talepten Hizmet Alıcı sorumlu olup Hizmet Sağlayıcı’nın Hizmet Alıcı’ya rücu hakkı saklıdır. Hizmet Alıcı’nın Hizmet Sağlayıcı’nın IT sistemine bağlantı için gerekli ekipmanına ilişkin teknik şartlar şunlardır:
1.	İnternet erişimi,
2.	cep telefonu numarası,
3.	e-posta adresi,
4.	web tarayıcısı.
5.	internet erişimi olan bilgisayar, tablet veya akıllı telefon
4.	Paket hizmeti süreklilik esasına göre temin edilir. Hizmet Alıcı bu hizmetlerin verilişinin askıya alınmasını talep etme hakkına sahip değildir.
5.	Hizmet Sağlayıcı Paket hizmeti bedellerinin tamamı veya bir kısmının Hizmet Alıcı tarafından geç ödenmesi durumunda hizmetlere erişimi durdurmak hakkına sahip olacaktır.
6.	Hizmet Sağlayıcı’nın görüşüne göre Hizmet Alıcı’nın Web Sitesi’n’in Hizmet Sağlayıcı’nın işiyle rekabet etme amacıyla veya kabul edilemez başka bir amaçla kullanılması halinde, Hizmet Sağlayıcı hizmetlerin teminini durdurmak veya hizmetlerin verilmesini herhangi bir zamanda reddetmek hakkına sahip olacaktır. İşbu maddeye aykırılık sebebiyle Hizmet Sağlayıcı nezdinde doğan her türlü zarardan da bizzat Hizmet Alıcı sorumludur.
 
MADDE 7 - kolayplan danışan takip yazılımı
1.	kolayplan Yazılımı’nin aktive edilmesi üzerine Hizmet Sağlayıcı Hizmet Alıcı’ya, Sözleşme’nin geçerlilik süresi ile sınırlı, gayrimünhasır ve yalnızca 7.2 maddesinde belirtilen kullanımlara ilişkin olmak üzere Web Sitesi’nde kullanmak üzere bir lisans vermektedir. Bu lisansın amacı Hizmet Alıcı’nın web sitesi ve özel mobil uygulamalar üzerinden kolayplan Yazılımı’na erişmesini sağlamaktadır. Bu lisans kolayplan Yazılımı’nın aktivasyon tarihindeki mevcut versiyonunu ve Hizmet Sağlayıcı tarafından Hizmet Alıcı’ya erişme izni verilmişse, Hizmet Sağlayıcı tarafından değiştirilen versiyonlarını yukarıda belirtilen zaman sınırı ve kullanma amacı ile sınırlı olmak üzere kullanma hakkını kapsar. Lisansın işbu maddede belirtilen kapsam dışında kullanması sonucunda 3. kişilerden gelebilecek her türlü talepten Hizmet Alıcı sorumlu olup Hizmet Sağlayıcı’nın Hizmet Alıcı’ya rücu hakkı saklıdır.
2.	Bu lisans yalnızca aşağıda belirtilen kullanımlar için verilmektedir:
1.	kolayplan Yazılımı’nın dağıtılması – Hizmet Alıcı tarafından seçilen yerde ve zamanda İnternet üzerinden kullanım
2.	kolayplan Yazılımı’nın çoğaltılması – kolayplan Yazılımı’nın düzgün çalışması için gerekli bilgisayar belleğinde veya bir başka analog cihazda geçici çoğaltımı (örn. tarama).
3.	Lisans Hizmet Sağlayıcı tarafından Hizmet Alıcı’ya erişme izni verildiği andan Sözleşme sona erinceye veya iptal edilinceye kadar sınırlı süreli olarak düzenlenmiştir.
4.	Aşağıdakiler de dahil olmak üzere kolayplan Yazılımı ile ilgili olarak Hizmet Alıcı’nın uygunsuz veya bu Sözleşme’yi ihlal eden davranışları olması durumunda Hizmet Sağlayıcı kolayplan Yazılımı’na erişimi bloke etme hakkına sahip olacaktır. Ayrıca aşağıdaki durumların gerçekleşmesi halinde 3. kişilerden gelebilecek her türlü talepten Hizmet Alıcı sorumlu olup Hizmet Sağlayıcı’nın Hizmet Alıcı’ya rücu hakkı saklıdır:
1.	kolayplan Yazılımı’nın başka kullanıcıların internet kullanımına zarar verecek şekilde kullanılması,
2.	Spam mail gönderilmesi,
3.	Kullanıcılar ve/veya Danışan’ların bilgileriyle oynanması,
4.	kolayplan Yazılımı’nın kaynak kodu ile oynanması,
5.	kolayplan Yazılımı’nı yetkisiz şekilde çoğaltma girişimleri,
6.	Hizmet Sağlayıcı’nın kişisel çıkarlarının ihlali,
7.	Hizmet Sağlayıcı’ya karşı haksız rekabet girişimleri,
8.	Sözleşme’nin ihlali,
Hizmet Sağlayıcı’nın lisansı iptal etme kararı Hizmet Alıcı tarafından Sipariş’te belirtilen e-posta adresine bildirilecektir.
 
MADDE 8 - Kişisel Bilgiler
 
1.	Hizmet Sağlayıcı kendisine Hizmet Alıcı tarafından verilen kişisel bilgilerin işlenmesini Hizmet Alıcı ile ayrı bir sözleşme yapılmasına gerek olmaksızın üçüncü şahıslara devredebilir ve Hizmet Alıcı bu hususu peşinen kabul eder. Bu Sözleşme’de belirtilen, kişisel bilgilerin işlenmesine ilişkin hükümler Hizmet Sağlayıcı’nın kişisel bilgilerin işlenmesini devrettiği üçüncü şahıs için de bağlayıcı olacaktır.
2.	Hizmet Alıcı sisteme girdiği kişisel bilgilerin tutulması, depolanması ve işlenmesi için ilgili bilgilerin sahiplerinden gerekli izinleri almış olmak yükümlülüğündedir.
 
MADDE 9 - Sözleşme Çerçevesinde Sorumluluk, Sözleşmenin Erken Feshi
 
1.	Hizmet Sağlayıcı’nın bu Sözleşme kapsamındaki Paket hizmetlerinin verilememesi veya gerektiği gibi verilememesinden kaynaklanan zararlardan sorumlu olmayacaktır.
2.	Hizmet Sağlayıcı, Hizmet Alıcı’nın uğrayacağı kar kaybı veya dolaylı zararlardan hiçbir şekilde sorumlu olmayacaktır. 
3.	İşbu Sözleşme’nin Madde 3 § 3’te belirtilen süresinin sonundan önce ve Hizmet Sağlayıcı’nın sorumlu olmadığı nedenlerle feshedilmesi durumunda, Hizmet Sağlayıcı Hizmet Alıcı’ya Kurulum Bedeli’ni ve fesih tarihine kadar olan üyelik kapsamında yapılan indirimleri fatura eder. Hizmet alıcı bu sözleşmeyi imzalamış olmak ile birlikte başka hiçbir ekstra bildirime ve cezai takibe gerek kalmaksızın düzenlenen bütün faturaları kabul eder.
4.	Hizmet Alıcı, işbu Sözleşme kapsamında aldığı Hizmetler kapsamında Hizmet Alıcı tarafından düzenlenen faturalardan birini 14 (ondört) günlük ödeme vadesinin dolmasına müteakip 29 (yirmi dokuz) gün içerisinde ödemediği takdirde, herhangi bir ihtara gerek olmaksızın temerrüde düşecektir. Hizmet Sağlayıcı bu durumda Hizmetler’i tek taraflı olarak durdurur ve/veya Sözleşme’yi herhangi bir bildirime gerek olmaksızın fesheder ve Kurulum Bedeli’ni ve fesih tarihine kadar olan üyelik kapsamında yapılan indirimleri Hizmet Alıcı’ya fatura eder. Hizmet Alıcı işbu Sözleşme’yi imzalamış olmak ile birlikte hiçbir bildirime ve cezai takibe gerek kalmaksızın düzenlenen bütün faturaları ve bu faturaları ödemeyi peşinen kabul, beyan ve taahhüt eder. Hizmet Alıcı işbu fatura tutarını ve Sözleşme’nin fesih tarihine kadar tahakkuk eden faturaların tamamını Sözleşme’nin feshi akabinde Hizmet’in Hizmet Sağlayıcı tarafından durdurulduğu tarihten itibaren en geç 14 (ondört) gün içerisinde telefon ile sözlü veya elektronik posta, sms, internet ve mobil uygulamalar ya da posta yolu ile yazılı olarak Hizmet Alıcı’ya bildirilen Hizmet Sağlayıcı’nın banka hesabına ödemekle yükümlü olacaktır. Aksi halde Hizmet Sağlayıcı ayrıca herhangi bir bildirime gerek olmaksızın yasal takibat sürecini başlatma hakkına sahiptir.
5.	İşbu Sözleşme kapsamında uygulanan ceza Hizmet Sağlayıcı’nın Hizmet Alıcı’ya verdiği hizmetler nedeniyle uğradığı zararın tamamını karşılamıyorsa, Hizmet Sağlayıcı, cezai tazminatı aşan zararlarını talep etmek hakkına sahip olacaktır.
 
MADDE 10 - Son hükümler
 
1.	Hizmet Sağlayıcı işbu Sözleşme’de belirtilen hizmetlerin veriliş şekliyle ilgili olarak tek taraflı değişiklik yapma hakkına sahiptir. Bu Sözleşme’ye göre yürürlüğe girecek olan fiyat listesi değişiklikleri hariç değişiklikler, yayınlandıkları tarihi izleyen ödeme döneminin sona ermesinden sonra geçerli olacaktır.
2.	Hizmet Sağlayıcı, IT ekipmanı üzerinde koruyucu bakım ve onarım işlemleri yapmak hakkına sahiptir. Bu işlemler Paket hizmetlerde aksaklığa veya bu hizmetlerin kullanılamamasına yol açabilir. Hizmet Sağlayıcı koruyucu bakım ve onarım çalışmalarının geceleri veya hafta sonunda yapılması için elinden gelen çabayı gösterecektir.
3.	İşbu Sözleşme’nin imzalandığı tarihte var olmayan veya öngörülemeyen, Taraflar’ın veya tek bir Taraf’ın çalışma imkânlarını kısmen veya tamamen, geçici veya daimi olarak durduracak şekilde ve derecede meydana gelen beşeri ve doğal afetler, harp, seferberlik, yangın, grev, lokavt vb. gibi haller ile Hizmet Sağlayıcı’nın sunucusunda meydana gelen bir kaza vb. Taraflar’ın kontrolü haricinde zuhur eden sair haller mücbir sebep sayılır. Mücbir sebebe maruz kalan Taraf durumu derhal diğer Taraf’a yazılı olarak bildirir ve mücbir sebep süresi boyunca Taraflar’ın edimleri askıya alınır. Mücbir sebepler ortadan kalkınca işbu Sözleşme kaldığı yerden devam eder. Mücbir sebep süresi boyunca hakları ifa edilmeyen Taraf’ın yükümlülükleri de askıya alınacaktır. Mücbir sebep halinin 10 günden fazla sürmesi halinde, Taraflar iyi niyetle durumu değerlendirerek birlikte veya ayrı ayrı fesih kararı alabileceklerdir. 
4.	Bu Sözleşme’de düzenlenmemiş olan hususlar Türkiye Cumhuriyeti’nin ilgili yasalarına tabi olacaktır.
5.	Taraflar arasındaki işbu Sözleşme’den kaynaklanan her türlü ihtilaf İstanbul Merkez Mahkemeleri ve İstanbul Merkez İcra Daireleri tarafından çözümlenecektir.
6.	Feragat beyanı yazılı olarak verilip, feragat eden ve lehine feragat verilen tarafından imzalanmadıkça verilmiş feragatname geçerli sayılmayacaktır. Taraflar’dan birinin bu Sözleşme’den doğan haklarından herhangi birini yerine getirmede ihmali veya gecikmesi feragat anlamına gelmeyeceği gibi herhangi bir hak veya yükümlülüğün kısmen kullanılması geri kalan hak veya yükümlülüğün sonradan kullanılmasını engellemez.
`